//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodPlaces.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GoodPlaces.Core.Resources.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        internal static string DistanceText {
            get {
                return ResourceManager.GetString("DistanceText", resourceCulture);
            }
        }
        
        internal static string EmailEntry {
            get {
                return ResourceManager.GetString("EmailEntry", resourceCulture);
            }
        }
        
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        internal static string MainPageButton {
            get {
                return ResourceManager.GetString("MainPageButton", resourceCulture);
            }
        }
        
        internal static string MainPageButtonPressed {
            get {
                return ResourceManager.GetString("MainPageButtonPressed", resourceCulture);
            }
        }
        
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        internal static string PasswordEntry {
            get {
                return ResourceManager.GetString("PasswordEntry", resourceCulture);
            }
        }
        
        internal static string PhoneNumberText {
            get {
                return ResourceManager.GetString("PhoneNumberText", resourceCulture);
            }
        }
    }
}
